[package]
name = "vanity25519"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
ed25519-dalek = "1.0.1"
rand = "0.7"
num_cpus = "0.2"
